# Generated by Django 4.1.2 on 2022-10-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_cores', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('hdd', models.IntegerField()),
                ('status', models.CharField(choices=[('started', 'started'), ('blocked', 'blocked'), ('stopped', 'stopped')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Vps',
            },
        ),
    ]
